### ISSUE TITLE
Access token is ignored

### ISSUE THREAD

**Issue by RichardInnocent** [RichardInnocent/semantic-versioning-maven#1]
The specified in `access-token` is not the token used to perform the pushes to the GitHub repository.

# Example
For example, consider the following specification:
```yaml
- name: Increment version
  id: incrementVersion
  uses: RichardInnocent/semantic-versioning-maven@v0.0.32
  with:
    access-token: fake
```

## Expected result
The push to GitHub with the changes fails as the token is invalid.

## Actual result
The push to GitHub succeeds, likely because it's authenticating using the default token.
